apiVersion: v1
kind: Service
metadata:
  name: edge-api-gateway
  labels:
    {{- include "edge-api-edgeway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "edge-api-edgeway.selectorLabels" . | nindent 4 }}
